dist: trusty
sudo: required
language: cpp
before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-add-repository -y ppa:beineri/opt-qt58-trusty
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-6 qt58tools qt58svg qt58webkit qt58script
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 50
script:
 - /opt/qt58/bin/qmake BulkClub.pro
 - make
