language: cpp
before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-add-repository -y ppa:beineri/opt-qt562
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-6 qt56tools qt56svg qt56webkit qt56script
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 50
script:
 - /opt/qt56/bin/qmake BulkClub.pro
 - make
